export enum TypeCategory {
  LITERATURE = 'LITERATURE',
  ECONOMY = 'ECONOMY',
  PHOTOGRAPHY_LIFE_SKILLS = 'PHOTOGRAPHY_LIFE_SKILLS',
  RAISE_UP_CHILD = 'RAISE_UP_CHILD',
  CHILDREN_BOOKS = 'CHILDREN_BOOKS',
  BIOLOGY_MEMORY = 'BIOLOGY_MEMORY',
  DIDACTIC = 'DIDACTIC',
  FOREIGN_LANGUAGE_BOOKS = 'FOREIGN_LANGUAGE_BOOKS',
}
